---
deployment:
  tasks:
    - export COMPOSER_HOME="$HOME/.composer"
    - /usr/local/bin/composer install --no-dev --prefer-dist --working-dir=$HOME/nativetutor.com
    - php $HOME/nativetutor.com/artisan config:cache
    - php $HOME/nativetutor.com/artisan route:cache
    - php $HOME/nativetutor.com/artisan view:cache
