---
deployment:
  tasks:
    # Set Composer home
    - export COMPOSER_HOME=$HOME/.composer

    # Install dependencies without dev packages and optimize autoloader
    - composer install --no-dev --optimize-autoloader

    # Cache Laravel configuration
    - php artisan config:cache

    # Cache routes
    - php artisan route:cache

    # Cache views
    - php artisan view:cache

    # Optional: Run database migrations (uncomment if needed)
    # - php artisan migrate --force
